packages:
  - .

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@tailwindcss/oxide"
  - esbuild
  - sharp
  - workerd

autoInstallPeers: false
publicHoistPattern:
  - "@tanstack/react-start-server"
minimumReleaseAge: 7200
